spring.config.import=optional:env.properties,optional:messages.properties

# -- Spring
spring.application.name=hospital-app-server
server.servlet.context-path=/api
spring.profiles.active=prod

# -- Hibernate
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow



